name: Run on Arch

on:
  schedule:
    - cron: '0 0 * * *' # Runs every 24 hours

jobs:
  run-setup-script:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm sudo
        echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel
        useradd -m -G wheel -s /bin/bash github
        echo 'github ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
        github bash <<EOF
          whoami
          pacman -Syu --noconfirm
          chmod +x setup.sh
          ./setup.sh
        EOF
